// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/containerd/containerd/api/types/descriptor.proto

package containerd.types;

import containerd.protobuf.GoGoProtos;

public final class DescriptorOuterClass {
  private DescriptorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DescriptorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:containerd.types.Descriptor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string media_type = 1;</code>
     */
    String getMediaType();
    /**
     * <code>string media_type = 1;</code>
     */
    com.google.protobuf.ByteString
        getMediaTypeBytes();

    /**
     * <code>string digest = 2;</code>
     */
    String getDigest();
    /**
     * <code>string digest = 2;</code>
     */
    com.google.protobuf.ByteString
        getDigestBytes();

    /**
     * <code>int64 size = 3;</code>
     */
    long getSize();

    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */
    int getAnnotationsCount();
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */
    boolean containsAnnotations(
        String key);
    /**
     * Use {@link #getAnnotationsMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getAnnotations();
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */
    java.util.Map<String, String>
    getAnnotationsMap();
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */

    String getAnnotationsOrDefault(
        String key,
        String defaultValue);
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */

    String getAnnotationsOrThrow(
        String key);
  }
  /**
   * <pre>
   * Descriptor describes a blob in a content store.
   * This descriptor can be used to reference content from an
   * oci descriptor found in a manifest.
   * See https://godoc.org/github.com/opencontainers/image-spec/specs-go/v1#Descriptor
   * </pre>
   *
   * Protobuf type {@code containerd.types.Descriptor}
   */
  public  static final class Descriptor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:containerd.types.Descriptor)
      DescriptorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Descriptor.newBuilder() to construct.
    private Descriptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Descriptor() {
      mediaType_ = "";
      digest_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Descriptor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              mediaType_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              digest_ = s;
              break;
            }
            case 24: {

              size_ = input.readInt64();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                annotations_ = com.google.protobuf.MapField.newMapField(
                    AnnotationsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<String, String>
              annotations__ = input.readMessage(
                  AnnotationsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              annotations_.getMutableMap().put(
                  annotations__.getKey(), annotations__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DescriptorOuterClass.internal_static_containerd_types_Descriptor_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetAnnotations();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DescriptorOuterClass.internal_static_containerd_types_Descriptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Descriptor.class, Builder.class);
    }

    private int bitField0_;
    public static final int MEDIA_TYPE_FIELD_NUMBER = 1;
    private volatile Object mediaType_;
    /**
     * <code>string media_type = 1;</code>
     */
    public String getMediaType() {
      Object ref = mediaType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mediaType_ = s;
        return s;
      }
    }
    /**
     * <code>string media_type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMediaTypeBytes() {
      Object ref = mediaType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mediaType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIGEST_FIELD_NUMBER = 2;
    private volatile Object digest_;
    /**
     * <code>string digest = 2;</code>
     */
    public String getDigest() {
      Object ref = digest_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        digest_ = s;
        return s;
      }
    }
    /**
     * <code>string digest = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDigestBytes() {
      Object ref = digest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        digest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_FIELD_NUMBER = 3;
    private long size_;
    /**
     * <code>int64 size = 3;</code>
     */
    public long getSize() {
      return size_;
    }

    public static final int ANNOTATIONS_FIELD_NUMBER = 5;
    private static final class AnnotationsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  DescriptorOuterClass.internal_static_containerd_types_Descriptor_AnnotationsEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> annotations_;
    private com.google.protobuf.MapField<String, String>
    internalGetAnnotations() {
      if (annotations_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AnnotationsDefaultEntryHolder.defaultEntry);
      }
      return annotations_;
    }

    public int getAnnotationsCount() {
      return internalGetAnnotations().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */

    public boolean containsAnnotations(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetAnnotations().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAnnotationsMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getAnnotations() {
      return getAnnotationsMap();
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */

    public java.util.Map<String, String> getAnnotationsMap() {
      return internalGetAnnotations().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */

    public String getAnnotationsOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetAnnotations().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */

    public String getAnnotationsOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetAnnotations().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMediaTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mediaType_);
      }
      if (!getDigestBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, digest_);
      }
      if (size_ != 0L) {
        output.writeInt64(3, size_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAnnotations(),
          AnnotationsDefaultEntryHolder.defaultEntry,
          5);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMediaTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mediaType_);
      }
      if (!getDigestBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, digest_);
      }
      if (size_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, size_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetAnnotations().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        annotations__ = AnnotationsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, annotations__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Descriptor)) {
        return super.equals(obj);
      }
      Descriptor other = (Descriptor) obj;

      if (!getMediaType()
          .equals(other.getMediaType())) return false;
      if (!getDigest()
          .equals(other.getDigest())) return false;
      if (getSize()
          != other.getSize()) return false;
      if (!internalGetAnnotations().equals(
          other.internalGetAnnotations())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEDIA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMediaType().hashCode();
      hash = (37 * hash) + DIGEST_FIELD_NUMBER;
      hash = (53 * hash) + getDigest().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
      if (!internalGetAnnotations().getMap().isEmpty()) {
        hash = (37 * hash) + ANNOTATIONS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAnnotations().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Descriptor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Descriptor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Descriptor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Descriptor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Descriptor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Descriptor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Descriptor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Descriptor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Descriptor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Descriptor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Descriptor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Descriptor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Descriptor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Descriptor describes a blob in a content store.
     * This descriptor can be used to reference content from an
     * oci descriptor found in a manifest.
     * See https://godoc.org/github.com/opencontainers/image-spec/specs-go/v1#Descriptor
     * </pre>
     *
     * Protobuf type {@code containerd.types.Descriptor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:containerd.types.Descriptor)
        DescriptorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DescriptorOuterClass.internal_static_containerd_types_Descriptor_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetAnnotations();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableAnnotations();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DescriptorOuterClass.internal_static_containerd_types_Descriptor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Descriptor.class, Builder.class);
      }

      // Construct using containerd.types.DescriptorOuterClass.Descriptor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        mediaType_ = "";

        digest_ = "";

        size_ = 0L;

        internalGetMutableAnnotations().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DescriptorOuterClass.internal_static_containerd_types_Descriptor_descriptor;
      }

      @Override
      public Descriptor getDefaultInstanceForType() {
        return Descriptor.getDefaultInstance();
      }

      @Override
      public Descriptor build() {
        Descriptor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Descriptor buildPartial() {
        Descriptor result = new Descriptor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.mediaType_ = mediaType_;
        result.digest_ = digest_;
        result.size_ = size_;
        result.annotations_ = internalGetAnnotations();
        result.annotations_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Descriptor) {
          return mergeFrom((Descriptor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Descriptor other) {
        if (other == Descriptor.getDefaultInstance()) return this;
        if (!other.getMediaType().isEmpty()) {
          mediaType_ = other.mediaType_;
          onChanged();
        }
        if (!other.getDigest().isEmpty()) {
          digest_ = other.digest_;
          onChanged();
        }
        if (other.getSize() != 0L) {
          setSize(other.getSize());
        }
        internalGetMutableAnnotations().mergeFrom(
            other.internalGetAnnotations());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Descriptor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Descriptor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object mediaType_ = "";
      /**
       * <code>string media_type = 1;</code>
       */
      public String getMediaType() {
        Object ref = mediaType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mediaType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string media_type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMediaTypeBytes() {
        Object ref = mediaType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mediaType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string media_type = 1;</code>
       */
      public Builder setMediaType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mediaType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string media_type = 1;</code>
       */
      public Builder clearMediaType() {
        
        mediaType_ = getDefaultInstance().getMediaType();
        onChanged();
        return this;
      }
      /**
       * <code>string media_type = 1;</code>
       */
      public Builder setMediaTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mediaType_ = value;
        onChanged();
        return this;
      }

      private Object digest_ = "";
      /**
       * <code>string digest = 2;</code>
       */
      public String getDigest() {
        Object ref = digest_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          digest_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string digest = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDigestBytes() {
        Object ref = digest_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          digest_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string digest = 2;</code>
       */
      public Builder setDigest(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        digest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string digest = 2;</code>
       */
      public Builder clearDigest() {
        
        digest_ = getDefaultInstance().getDigest();
        onChanged();
        return this;
      }
      /**
       * <code>string digest = 2;</code>
       */
      public Builder setDigestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        digest_ = value;
        onChanged();
        return this;
      }

      private long size_ ;
      /**
       * <code>int64 size = 3;</code>
       */
      public long getSize() {
        return size_;
      }
      /**
       * <code>int64 size = 3;</code>
       */
      public Builder setSize(long value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 size = 3;</code>
       */
      public Builder clearSize() {
        
        size_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> annotations_;
      private com.google.protobuf.MapField<String, String>
      internalGetAnnotations() {
        if (annotations_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AnnotationsDefaultEntryHolder.defaultEntry);
        }
        return annotations_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableAnnotations() {
        onChanged();;
        if (annotations_ == null) {
          annotations_ = com.google.protobuf.MapField.newMapField(
              AnnotationsDefaultEntryHolder.defaultEntry);
        }
        if (!annotations_.isMutable()) {
          annotations_ = annotations_.copy();
        }
        return annotations_;
      }

      public int getAnnotationsCount() {
        return internalGetAnnotations().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */

      public boolean containsAnnotations(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetAnnotations().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAnnotationsMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getAnnotations() {
        return getAnnotationsMap();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */

      public java.util.Map<String, String> getAnnotationsMap() {
        return internalGetAnnotations().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */

      public String getAnnotationsOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetAnnotations().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */

      public String getAnnotationsOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetAnnotations().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAnnotations() {
        internalGetMutableAnnotations().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */

      public Builder removeAnnotations(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableAnnotations().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableAnnotations() {
        return internalGetMutableAnnotations().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */
      public Builder putAnnotations(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableAnnotations().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 5;</code>
       */

      public Builder putAllAnnotations(
          java.util.Map<String, String> values) {
        internalGetMutableAnnotations().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:containerd.types.Descriptor)
    }

    // @@protoc_insertion_point(class_scope:containerd.types.Descriptor)
    private static final Descriptor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Descriptor();
    }

    public static Descriptor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Descriptor>
        PARSER = new com.google.protobuf.AbstractParser<Descriptor>() {
      @Override
      public Descriptor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Descriptor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Descriptor> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Descriptor> getParserForType() {
      return PARSER;
    }

    @Override
    public Descriptor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containerd_types_Descriptor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containerd_types_Descriptor_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containerd_types_Descriptor_AnnotationsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containerd_types_Descriptor_AnnotationsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n;github.com/containerd/containerd/api/t" +
      "ypes/descriptor.proto\022\020containerd.types\032" +
      "\024gogoproto/gogo.proto\"\266\001\n\nDescriptor\022\022\n\n" +
      "media_type\030\001 \001(\t\022\016\n\006digest\030\002 \001(\t\022\014\n\004size" +
      "\030\003 \001(\003\022B\n\013annotations\030\005 \003(\0132-.containerd" +
      ".types.Descriptor.AnnotationsEntry\0322\n\020An" +
      "notationsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001" +
      "(\t:\0028\001B2Z0github.com/containerd/containe" +
      "rd/api/types;typesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_containerd_types_Descriptor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_containerd_types_Descriptor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containerd_types_Descriptor_descriptor,
        new String[] { "MediaType", "Digest", "Size", "Annotations", });
    internal_static_containerd_types_Descriptor_AnnotationsEntry_descriptor =
      internal_static_containerd_types_Descriptor_descriptor.getNestedTypes().get(0);
    internal_static_containerd_types_Descriptor_AnnotationsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containerd_types_Descriptor_AnnotationsEntry_descriptor,
        new String[] { "Key", "Value", });
    GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
