// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/containerd/containerd/api/types/platform.proto

package containerd.types;

import containerd.protobuf.GoGoProtos;

public final class PlatformOuterClass {
  private PlatformOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlatformOrBuilder extends
      // @@protoc_insertion_point(interface_extends:containerd.types.Platform)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string os = 1 [(.gogoproto.customname) = "OS"];</code>
     */
    String getOs();
    /**
     * <code>string os = 1 [(.gogoproto.customname) = "OS"];</code>
     */
    com.google.protobuf.ByteString
        getOsBytes();

    /**
     * <code>string architecture = 2;</code>
     */
    String getArchitecture();
    /**
     * <code>string architecture = 2;</code>
     */
    com.google.protobuf.ByteString
        getArchitectureBytes();

    /**
     * <code>string variant = 3;</code>
     */
    String getVariant();
    /**
     * <code>string variant = 3;</code>
     */
    com.google.protobuf.ByteString
        getVariantBytes();
  }
  /**
   * <pre>
   * Platform follows the structure of the OCI platform specification, from
   * descriptors.
   * </pre>
   *
   * Protobuf type {@code containerd.types.Platform}
   */
  public  static final class Platform extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:containerd.types.Platform)
      PlatformOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Platform.newBuilder() to construct.
    private Platform(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Platform() {
      os_ = "";
      architecture_ = "";
      variant_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Platform(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              os_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              architecture_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              variant_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlatformOuterClass.internal_static_containerd_types_Platform_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlatformOuterClass.internal_static_containerd_types_Platform_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Platform.class, Builder.class);
    }

    public static final int OS_FIELD_NUMBER = 1;
    private volatile Object os_;
    /**
     * <code>string os = 1 [(.gogoproto.customname) = "OS"];</code>
     */
    public String getOs() {
      Object ref = os_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        os_ = s;
        return s;
      }
    }
    /**
     * <code>string os = 1 [(.gogoproto.customname) = "OS"];</code>
     */
    public com.google.protobuf.ByteString
        getOsBytes() {
      Object ref = os_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        os_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARCHITECTURE_FIELD_NUMBER = 2;
    private volatile Object architecture_;
    /**
     * <code>string architecture = 2;</code>
     */
    public String getArchitecture() {
      Object ref = architecture_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        architecture_ = s;
        return s;
      }
    }
    /**
     * <code>string architecture = 2;</code>
     */
    public com.google.protobuf.ByteString
        getArchitectureBytes() {
      Object ref = architecture_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        architecture_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VARIANT_FIELD_NUMBER = 3;
    private volatile Object variant_;
    /**
     * <code>string variant = 3;</code>
     */
    public String getVariant() {
      Object ref = variant_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        variant_ = s;
        return s;
      }
    }
    /**
     * <code>string variant = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVariantBytes() {
      Object ref = variant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        variant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, os_);
      }
      if (!getArchitectureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, architecture_);
      }
      if (!getVariantBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, variant_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, os_);
      }
      if (!getArchitectureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, architecture_);
      }
      if (!getVariantBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, variant_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Platform)) {
        return super.equals(obj);
      }
      Platform other = (Platform) obj;

      if (!getOs()
          .equals(other.getOs())) return false;
      if (!getArchitecture()
          .equals(other.getArchitecture())) return false;
      if (!getVariant()
          .equals(other.getVariant())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OS_FIELD_NUMBER;
      hash = (53 * hash) + getOs().hashCode();
      hash = (37 * hash) + ARCHITECTURE_FIELD_NUMBER;
      hash = (53 * hash) + getArchitecture().hashCode();
      hash = (37 * hash) + VARIANT_FIELD_NUMBER;
      hash = (53 * hash) + getVariant().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Platform parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Platform parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Platform parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Platform parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Platform parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Platform parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Platform parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Platform parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Platform parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Platform parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Platform parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Platform parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Platform prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Platform follows the structure of the OCI platform specification, from
     * descriptors.
     * </pre>
     *
     * Protobuf type {@code containerd.types.Platform}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:containerd.types.Platform)
        PlatformOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlatformOuterClass.internal_static_containerd_types_Platform_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlatformOuterClass.internal_static_containerd_types_Platform_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Platform.class, Builder.class);
      }

      // Construct using containerd.types.PlatformOuterClass.Platform.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        os_ = "";

        architecture_ = "";

        variant_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PlatformOuterClass.internal_static_containerd_types_Platform_descriptor;
      }

      @Override
      public Platform getDefaultInstanceForType() {
        return Platform.getDefaultInstance();
      }

      @Override
      public Platform build() {
        Platform result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Platform buildPartial() {
        Platform result = new Platform(this);
        result.os_ = os_;
        result.architecture_ = architecture_;
        result.variant_ = variant_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Platform) {
          return mergeFrom((Platform)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Platform other) {
        if (other == Platform.getDefaultInstance()) return this;
        if (!other.getOs().isEmpty()) {
          os_ = other.os_;
          onChanged();
        }
        if (!other.getArchitecture().isEmpty()) {
          architecture_ = other.architecture_;
          onChanged();
        }
        if (!other.getVariant().isEmpty()) {
          variant_ = other.variant_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Platform parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Platform) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object os_ = "";
      /**
       * <code>string os = 1 [(.gogoproto.customname) = "OS"];</code>
       */
      public String getOs() {
        Object ref = os_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          os_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string os = 1 [(.gogoproto.customname) = "OS"];</code>
       */
      public com.google.protobuf.ByteString
          getOsBytes() {
        Object ref = os_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          os_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string os = 1 [(.gogoproto.customname) = "OS"];</code>
       */
      public Builder setOs(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        os_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string os = 1 [(.gogoproto.customname) = "OS"];</code>
       */
      public Builder clearOs() {
        
        os_ = getDefaultInstance().getOs();
        onChanged();
        return this;
      }
      /**
       * <code>string os = 1 [(.gogoproto.customname) = "OS"];</code>
       */
      public Builder setOsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        os_ = value;
        onChanged();
        return this;
      }

      private Object architecture_ = "";
      /**
       * <code>string architecture = 2;</code>
       */
      public String getArchitecture() {
        Object ref = architecture_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          architecture_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string architecture = 2;</code>
       */
      public com.google.protobuf.ByteString
          getArchitectureBytes() {
        Object ref = architecture_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          architecture_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string architecture = 2;</code>
       */
      public Builder setArchitecture(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        architecture_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string architecture = 2;</code>
       */
      public Builder clearArchitecture() {
        
        architecture_ = getDefaultInstance().getArchitecture();
        onChanged();
        return this;
      }
      /**
       * <code>string architecture = 2;</code>
       */
      public Builder setArchitectureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        architecture_ = value;
        onChanged();
        return this;
      }

      private Object variant_ = "";
      /**
       * <code>string variant = 3;</code>
       */
      public String getVariant() {
        Object ref = variant_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          variant_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string variant = 3;</code>
       */
      public com.google.protobuf.ByteString
          getVariantBytes() {
        Object ref = variant_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          variant_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string variant = 3;</code>
       */
      public Builder setVariant(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        variant_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string variant = 3;</code>
       */
      public Builder clearVariant() {
        
        variant_ = getDefaultInstance().getVariant();
        onChanged();
        return this;
      }
      /**
       * <code>string variant = 3;</code>
       */
      public Builder setVariantBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        variant_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:containerd.types.Platform)
    }

    // @@protoc_insertion_point(class_scope:containerd.types.Platform)
    private static final Platform DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Platform();
    }

    public static Platform getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Platform>
        PARSER = new com.google.protobuf.AbstractParser<Platform>() {
      @Override
      public Platform parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Platform(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Platform> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Platform> getParserForType() {
      return PARSER;
    }

    @Override
    public Platform getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_containerd_types_Platform_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_containerd_types_Platform_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n9github.com/containerd/containerd/api/t" +
      "ypes/platform.proto\022\020containerd.types\032\024g" +
      "ogoproto/gogo.proto\"E\n\010Platform\022\022\n\002os\030\001 " +
      "\001(\tB\006\342\336\037\002OS\022\024\n\014architecture\030\002 \001(\t\022\017\n\007var" +
      "iant\030\003 \001(\tB2Z0github.com/containerd/cont" +
      "ainerd/api/types;typesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_containerd_types_Platform_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_containerd_types_Platform_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_containerd_types_Platform_descriptor,
        new String[] { "Os", "Architecture", "Variant", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(GoGoProtos.customname);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
